# checkov:skip=CKV_DOCKER_2:Healthcheck defined in docker-compose.yml
# checkov:skip=CKV_DOCKER_3:Base image runs as valkey user (UID 999)
FROM dhi.io/valkey:8.1@sha256:5f33330d05cbe6665af387cea4adc955b93cf86eb3cabc676965b4a38cabef2c
