#cloud-config
# Polis VM Cloud-Init Configuration
# This file provisions a complete Polis environment in Multipass

package_update: true
package_upgrade: true

# Install required system packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - jq
  - git
  - build-essential

# Configure system settings for Docker and Sysbox
write_files:
  # Docker daemon configuration for Sysbox
  - path: /etc/docker/daemon.json
    content: |
      {
        "runtimes": {
          "sysbox-runc": {
            "path": "/usr/bin/sysbox-runc"
          }
        },
        "default-address-pools": [
          {
            "base": "172.20.0.0/16",
            "size": 24
          }
        ]
      }
    permissions: '0644'

runcmd:
  # 1. Install Docker Engine
  - |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    
  # 2. Install Sysbox (required for workspace isolation)
  - |
    SYSBOX_VERSION="0.6.4"
    wget https://downloads.nestybox.com/sysbox/releases/v${SYSBOX_VERSION}/sysbox-ce_${SYSBOX_VERSION}-0.linux_amd64.deb
    apt-get install -y ./sysbox-ce_${SYSBOX_VERSION}-0.linux_amd64.deb
    rm sysbox-ce_${SYSBOX_VERSION}-0.linux_amd64.deb
    
  # 3. Restart Docker to pick up Sysbox runtime
  - systemctl restart docker
  
  # 4. Add ubuntu user to docker group
  - usermod -aG docker ubuntu
  
  # 5. Clone Polis repository
  - |
    su - ubuntu -c "cd /home/ubuntu && git clone --recursive https://github.com/OdraLabsHQ/polis.git"
  
  # 6. Set up Polis environment
  - |
    su - ubuntu -c "cd /home/ubuntu/polis && cp agents/openclaw/config/env.example .env"
  
  # 7. Verify installation
  - docker info | grep -i sysbox
  - docker run --runtime=sysbox-runc --rm alpine echo "Sysbox ready!"

final_message: |
  Polis VM is ready!
  
  Next steps:
  1. Access VM: multipass shell polis-vm
  2. Configure API keys: nano ~/polis/.env
  3. Start Polis: cd ~/polis && ./tools/polis.sh init --agent=openclaw
  
  The VM has:
  - Docker Engine with docker-compose
  - Sysbox runtime (sysbox-runc)
  - Polis cloned to ~/polis
  - Ubuntu user in docker group
