# agents/<name>/compose.override.yaml
# Merged via: docker compose -f deploy/docker-compose.yml -f agents/<name>/compose.override.yaml
# All relative paths resolve relative to deploy/ (first -f file), NOT this file.
services:
  workspace:
    # ports:
    #   - "${CHANGEME_HOST_PORT:-0}:0"
    healthcheck:
      test: ["CMD-SHELL", "systemctl is-active polis-init.service && ip route | grep -q default"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
