# agents/<name>/compose.override.yaml
# Merged via: docker compose -f docker-compose.yml -f agents/<name>/compose.override.yaml
# All relative paths resolve relative to deploy/ (first -f file), NOT this file.
services:
  workspace:
    # ports:
    #   - "${CHANGEME_HOST_PORT:-0}:0"
    volumes:
      - ../agents/<name>/:/tmp/agents/<name>/:ro
      - ../agents/<name>/config/agent.service:/etc/systemd/system/<name>.service:ro
      - ../.env:/run/<name>-env:ro
    healthcheck:
      test: ["CMD-SHELL", "systemctl is-active polis-init.service && systemctl is-active <name>.service && ip route | grep -q default"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
