# agents/openclaw/compose.override.yaml
# Merged via: docker compose -f docker-compose.yml -f agents/openclaw/compose.override.yaml
# All relative paths resolve relative to the first -f file (repository root).
services:
  workspace:
    ports:
      - "${OPENCLAW_HOST_PORT:-18789}:18789"
    env_file:
      - ./.env
    environment:
      - OPENCLAW_GATEWAY_PORT=${OPENCLAW_GATEWAY_PORT:-18789}
    volumes:
      - ./agents/openclaw/:/tmp/agents/openclaw/:ro
      - ./agents/openclaw/config/openclaw.service:/etc/systemd/system/openclaw.service:ro
      - ./.env:/run/openclaw-env:ro
    healthcheck:
      # REPLACES the base healthcheck entirely.
      # Always include polis-init.service AND ip route checks.
      test: ["CMD-SHELL", "systemctl is-active polis-init.service && systemctl is-active openclaw.service && ip route | grep -q default"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
