# agents/openclaw/compose.override.yaml
# Merged via: docker compose -f docker-compose.yml -f agents/openclaw/compose.override.yaml
# All relative paths resolve relative to deploy/ (first -f file), NOT this file.
services:
  workspace:
    ports:
      - "${OPENCLAW_HOST_PORT:-18789}:18789"
    networks:
      internal-bridge: {}
      host-access:
        ipv4_address: 10.40.1.2
    env_file:
      - .env
    environment:
      - OPENCLAW_GATEWAY_PORT=${OPENCLAW_GATEWAY_PORT:-18789}
    volumes:
      - ./agents/openclaw/:/tmp/agents/openclaw/:ro
      - ./agents/openclaw/config/openclaw.service:/etc/systemd/system/openclaw.service:ro
      - ./agents/openclaw/config/SOUL.md:/usr/local/share/openclaw/SOUL.md:ro
      - ./agents/openclaw/scripts/polis-mcp-call.sh:/usr/local/share/openclaw/scripts/polis-mcp-call.sh:ro
      - ./agents/openclaw/scripts/polis-report-block.sh:/usr/local/share/openclaw/scripts/polis-report-block.sh:ro
      - ./agents/openclaw/scripts/polis-check-status.sh:/usr/local/share/openclaw/scripts/polis-check-status.sh:ro
      - ./agents/openclaw/scripts/polis-list-pending.sh:/usr/local/share/openclaw/scripts/polis-list-pending.sh:ro
      - ./agents/openclaw/scripts/polis-security-status.sh:/usr/local/share/openclaw/scripts/polis-security-status.sh:ro
      - ./agents/openclaw/scripts/polis-security-log.sh:/usr/local/share/openclaw/scripts/polis-security-log.sh:ro
      - ./.env:/run/openclaw-env:ro
    healthcheck:
      # REPLACES the base healthcheck entirely.
      # Always include polis-init.service AND ip route checks.
      test: ["CMD-SHELL", "systemctl is-active polis-init.service && systemctl is-active openclaw.service && ip route | grep -q default"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

networks:
  host-access:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.40.1.0/24
