#!/bin/bash
set -euo pipefail

# =============================================================================
# Valkey Secrets Generator
# Generates passwords, ACL configuration, and credential references
# for all Valkey service users.
# =============================================================================

# Output directory (default: ./secrets)
OUTPUT_DIR="${1:-./secrets}"
# Project root for .env file (default: parent of output dir)
PROJECT_ROOT="${2:-$(cd "$(dirname "${OUTPUT_DIR}")" && pwd)}"
ENV_FILE="${PROJECT_ROOT}/.env"

echo "=== Valkey Secrets Generator ==="
echo "Output directory: ${OUTPUT_DIR}"

# Create output directory if it doesn't exist
mkdir -p "${OUTPUT_DIR}"

# =============================================================================
# Password Generation
# Generate unique 32-character alphanumeric passwords for each user
# =============================================================================

echo ""
echo "--- Generating passwords ---"

generate_password() {
    openssl rand -base64 32 | tr -d '/+=' | head -c 32
}

PASS_MCP_AGENT="$(generate_password)"
PASS_MCP_ADMIN="$(generate_password)"
PASS_LOG_WRITER="$(generate_password)"
PASS_HEALTHCHECK="$(generate_password)"
PASS_GOV_REQMOD="$(generate_password)"
PASS_GOV_RESPMOD="$(generate_password)"
DLP_PASS="$(generate_password)"

echo "Generated 7 unique passwords (32 characters each)."

# =============================================================================
# SHA-256 Hash Generation
# Hash each password for use in the ACL file
# =============================================================================

echo ""
echo "--- Computing SHA-256 hashes ---"

hash_password() {
    echo -n "$1" | sha256sum | awk '{print $1}'
}

HASH_MCP_AGENT="$(hash_password "${PASS_MCP_AGENT}")"
HASH_MCP_ADMIN="$(hash_password "${PASS_MCP_ADMIN}")"
HASH_LOG_WRITER="$(hash_password "${PASS_LOG_WRITER}")"
HASH_HEALTHCHECK="$(hash_password "${PASS_HEALTHCHECK}")"
HASH_GOV_REQMOD="$(hash_password "${PASS_GOV_REQMOD}")"
HASH_GOV_RESPMOD="$(hash_password "${PASS_GOV_RESPMOD}")"
HASH_DLP="$(hash_password "${DLP_PASS}")"

echo "SHA-256 hashes computed for all users."

# =============================================================================
# Create valkey_password.txt
# Contains the healthcheck user password (used by Docker health check)
# =============================================================================

echo ""
echo "--- Creating valkey_password.txt ---"

cat > "${OUTPUT_DIR}/valkey_password.txt" <<EOF
${PASS_HEALTHCHECK}
EOF

echo "valkey_password.txt created (healthcheck password)."

# =============================================================================
# Create valkey_users.acl
# ACL rules with SHA-256 hashed passwords for all users
# Includes: governance ICAP users, MCP users, utility users
# =============================================================================

echo ""
echo "--- Creating valkey_users.acl ---"

cat > "${OUTPUT_DIR}/valkey_users.acl" <<EOF
user default off
user governance-reqmod on #${HASH_GOV_REQMOD} ~polis:ott:* ~polis:blocked:* ~polis:log:* -@all +get +set +setnx +exists +zadd
user governance-respmod on #${HASH_GOV_RESPMOD} ~polis:ott:* ~polis:blocked:* ~polis:approved:* ~polis:log:* -@all +get +del +setex +exists +zadd
user mcp-agent on #${HASH_MCP_AGENT} ~polis:blocked:* ~polis:approved:* ~polis:config:security_level ~polis:log:events -@all +GET +SETEX +EXISTS +SCAN +PING +ZREVRANGE
user mcp-admin on #${HASH_MCP_ADMIN} ~polis:* +@all -@dangerous -FLUSHALL -FLUSHDB -DEBUG -CONFIG -SHUTDOWN
user log-writer on #${HASH_LOG_WRITER} ~polis:log:events -@all +ZADD +ZRANGEBYSCORE +ZCARD +PING
user healthcheck on #${HASH_HEALTHCHECK} -@all +PING +INFO
user dlp-reader on #${HASH_DLP} ~polis:config:security_level -@all +GET +PING
EOF

echo "valkey_users.acl created (8 user entries)."

# =============================================================================
# Create valkey_dlp_password.txt
# Contains the dlp-reader user password (used by DLP module Docker secret)
# =============================================================================

echo ""
echo "--- Creating valkey_dlp_password.txt ---"

echo -n "$DLP_PASS" > "${OUTPUT_DIR}/valkey_dlp_password.txt"

echo "valkey_dlp_password.txt created (dlp-reader password)."

# =============================================================================
# Create credentials.env.example
# Plaintext credentials for development reference
# =============================================================================

echo ""
echo "--- Creating credentials.env.example ---"

cat > "${OUTPUT_DIR}/credentials.env.example" <<EOF
# Valkey Credentials Reference
# Generated by generate-valkey-secrets.sh
# These are plaintext credentials for development reference only.
# Production uses Docker secrets with hashed passwords in the ACL file.

VALKEY_MCP_AGENT_PASS=${PASS_MCP_AGENT}
VALKEY_MCP_ADMIN_PASS=${PASS_MCP_ADMIN}
VALKEY_LOG_WRITER_PASS=${PASS_LOG_WRITER}
VALKEY_HEALTHCHECK_PASS=${PASS_HEALTHCHECK}
VALKEY_GOV_REQMOD_PASS=${PASS_GOV_REQMOD}
VALKEY_GOV_RESPMOD_PASS=${PASS_GOV_RESPMOD}
VALKEY_DLP_USER=dlp-reader
VALKEY_DLP_PASS=${DLP_PASS}
EOF

echo "credentials.env.example created (8 user credentials)."

# =============================================================================
# Write required env vars to .env
# Docker-compose needs VALKEY_MCP_AGENT_PASS for the mcp-agent service
# =============================================================================

echo ""
echo "--- Updating .env file ---"

if [[ -f "$ENV_FILE" ]]; then
    # Remove any existing VALKEY_ vars to avoid duplicates
    sed -i '/^VALKEY_MCP_AGENT_PASS=/d' "$ENV_FILE"
    sed -i '/^VALKEY_REQMOD_PASS=/d' "$ENV_FILE"
    sed -i '/^VALKEY_RESPMOD_PASS=/d' "$ENV_FILE"
fi

# Append passwords docker-compose needs
echo "VALKEY_MCP_AGENT_PASS=${PASS_MCP_AGENT}" >> "$ENV_FILE"
echo "VALKEY_REQMOD_PASS=${PASS_GOV_REQMOD}" >> "$ENV_FILE"
echo "VALKEY_RESPMOD_PASS=${PASS_GOV_RESPMOD}" >> "$ENV_FILE"

echo "VALKEY_MCP_AGENT_PASS, VALKEY_REQMOD_PASS, VALKEY_RESPMOD_PASS written to ${ENV_FILE}"

# =============================================================================
# Set File Permissions
# =============================================================================

echo ""
echo "--- Setting file permissions ---"

chmod 600 "${OUTPUT_DIR}/valkey_password.txt"
chmod 600 "${OUTPUT_DIR}/valkey_users.acl"
chmod 600 "${OUTPUT_DIR}/valkey_dlp_password.txt"
chmod 600 "${OUTPUT_DIR}/credentials.env.example"

echo "Permissions set: all files=600"

echo ""
echo "=== Secrets generation complete ==="
echo "Files created in: ${OUTPUT_DIR}"
echo "  valkey_password.txt      (healthcheck password)"
echo "  valkey_users.acl         (ACL with hashed passwords)"
echo "  valkey_dlp_password.txt  (dlp-reader password)"
echo "  credentials.env.example  (plaintext reference)"
