#!/bin/bash
set -euo pipefail

# =============================================================================
# Valkey Secrets Generator
# Generates passwords, ACL configuration, and credential references
# for all Valkey service users.
# =============================================================================

# Output directory (default: ./secrets)
OUTPUT_DIR="${1:-./secrets}"

echo "=== Valkey Secrets Generator ==="
echo "Output directory: ${OUTPUT_DIR}"

# Create output directory if it doesn't exist
mkdir -p "${OUTPUT_DIR}"

# =============================================================================
# Password Generation
# Generate four unique 32-character alphanumeric passwords
# =============================================================================

echo ""
echo "--- Generating passwords ---"

generate_password() {
    openssl rand -base64 32 | tr -d '/+=' | head -c 32
}

PASS_MCP_AGENT="$(generate_password)"
PASS_MCP_ADMIN="$(generate_password)"
PASS_LOG_WRITER="$(generate_password)"
PASS_HEALTHCHECK="$(generate_password)"

echo "Generated 4 unique passwords (32 characters each)."

# =============================================================================
# SHA-256 Hash Generation
# Hash each password for use in the ACL file
# =============================================================================

echo ""
echo "--- Computing SHA-256 hashes ---"

hash_password() {
    echo -n "$1" | sha256sum | awk '{print $1}'
}

HASH_MCP_AGENT="$(hash_password "${PASS_MCP_AGENT}")"
HASH_MCP_ADMIN="$(hash_password "${PASS_MCP_ADMIN}")"
HASH_LOG_WRITER="$(hash_password "${PASS_LOG_WRITER}")"
HASH_HEALTHCHECK="$(hash_password "${PASS_HEALTHCHECK}")"

echo "SHA-256 hashes computed for all users."

# =============================================================================
# Create valkey_password.txt
# Contains the healthcheck user password (used by Docker health check)
# =============================================================================

echo ""
echo "--- Creating valkey_password.txt ---"

cat > "${OUTPUT_DIR}/valkey_password.txt" <<EOF
${PASS_HEALTHCHECK}
EOF

echo "valkey_password.txt created (healthcheck password)."

# =============================================================================
# Create valkey_users.acl
# ACL rules with SHA-256 hashed passwords for all users
# =============================================================================

echo ""
echo "--- Creating valkey_users.acl ---"

cat > "${OUTPUT_DIR}/valkey_users.acl" <<EOF
user default off
user mcp-agent on #${HASH_MCP_AGENT} ~molis:blocked:* ~molis:approved:* ~molis:config:* +@read +@write +@connection -@admin -@dangerous -DEL -UNLINK
user mcp-admin on #${HASH_MCP_ADMIN} ~molis:* +@all -@dangerous -FLUSHALL -FLUSHDB -DEBUG -CONFIG -SHUTDOWN
user log-writer on #${HASH_LOG_WRITER} ~molis:log:events +ZADD +ZRANGEBYSCORE +ZCARD +PING -@all
user healthcheck on #${HASH_HEALTHCHECK} +PING +INFO -@all
EOF

echo "valkey_users.acl created (5 user entries)."

# =============================================================================
# Create credentials.env.example
# Plaintext credentials for reference (not used in production)
# =============================================================================

echo ""
echo "--- Creating credentials.env.example ---"

cat > "${OUTPUT_DIR}/credentials.env.example" <<EOF
# Valkey Credentials Reference
# Generated by generate-valkey-secrets.sh
# These are plaintext credentials for development reference only.
# Production uses Docker secrets with hashed passwords in the ACL file.

VALKEY_MCP_AGENT_PASSWORD=${PASS_MCP_AGENT}
VALKEY_MCP_ADMIN_PASSWORD=${PASS_MCP_ADMIN}
VALKEY_LOG_WRITER_PASSWORD=${PASS_LOG_WRITER}
VALKEY_HEALTHCHECK_PASSWORD=${PASS_HEALTHCHECK}
EOF

echo "credentials.env.example created (4 user credentials)."

# =============================================================================
# Set File Permissions
# All generated files set to 600 (owner read/write only)
# =============================================================================

echo ""
echo "--- Setting file permissions ---"

chmod 600 "${OUTPUT_DIR}/valkey_password.txt"
chmod 600 "${OUTPUT_DIR}/valkey_users.acl"
chmod 600 "${OUTPUT_DIR}/credentials.env.example"

echo "Permissions set: all files=600"

echo ""
echo "=== Secrets generation complete ==="
echo "Files created in: ${OUTPUT_DIR}"
echo "  valkey_password.txt      (healthcheck password)"
echo "  valkey_users.acl         (ACL with hashed passwords)"
echo "  credentials.env.example  (plaintext reference)"
