# Polis Dev Installer for Windows — installs from local build artifacts
# Usage: .\scripts\install-dev.ps1 [-RepoDir C:\path\to\polis]
#
# Does NOT use `polis start`. Creates the VM and provisions it directly via
# multipass commands so the dev flow is fully self-contained and debuggable.
[CmdletBinding()]
param(
    [string]$RepoDir = (Split-Path $PSScriptRoot -Parent)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$MultipassMin = [version]"1.16.0"
$InstallDir   = Join-Path $env:USERPROFILE ".polis"

function Write-Info { param($msg) Write-Host "[INFO]  $msg" -ForegroundColor Cyan }
function Write-Ok   { param($msg) Write-Host "[OK]    $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "[WARN]  $msg" -ForegroundColor Yellow }
function Write-Err  { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red }

# ── Multipass check ───────────────────────────────────────────────────────────

function Assert-Multipass {
    if (-not (Get-Command multipass -ErrorAction SilentlyContinue)) {
        Write-Err "Multipass is required but not installed."
        Write-Host "  Install: https://multipass.run/install"
        exit 1
    }

    $verLine = (& multipass version 2>$null | Select-Object -First 1) -replace '\s+', ' '
    $verStr  = ($verLine -split ' ')[1]
    if ($verStr) {
        $verClean = $verStr -replace '\+.*', ''
        try {
            $installed = [version]$verClean
            if ($installed -lt $MultipassMin) {
                Write-Err "Multipass $verStr is too old (need >= $MultipassMin)."
                Write-Host "  Update: https://multipass.run/install"
                exit 1
            }
            Write-Ok "Multipass $verStr OK"
        } catch {
            Write-Warn "Could not parse Multipass version '$verStr' — proceeding anyway."
        }
    }
}

# ── CLI install ───────────────────────────────────────────────────────────────

function Install-Cli {
    $bin = Join-Path $RepoDir "cli\target\release\polis.exe"
    if (-not (Test-Path $bin)) {
        Write-Err "CLI binary not found at $bin"
        Write-Host "  Build it first: cd $RepoDir; just build-windows"
        exit 1
    }
    $dest = Join-Path $InstallDir "bin"
    New-Item -ItemType Directory -Force -Path $dest | Out-Null
    Copy-Item $bin (Join-Path $dest "polis.exe") -Force
    Write-Ok "Installed CLI from $bin"
}

# ── PATH ──────────────────────────────────────────────────────────────────────

function Add-ToUserPath {
    $binDir  = Join-Path $InstallDir "bin"
    $current = [System.Environment]::GetEnvironmentVariable("PATH", "User")
    if ($current -notlike "*$binDir*") {
        [System.Environment]::SetEnvironmentVariable("PATH", "$current;$binDir", "User")
        $env:PATH += ";$binDir"
        Write-Ok "Added $binDir to user PATH"
    }
}

# ── VM init + image loading ───────────────────────────────────────────────────

function Invoke-PolisInit {
    $imagesTar  = Join-Path $RepoDir ".build\polis-images.tar.zst"
    $configTar  = Join-Path $RepoDir ".build\assets\polis-setup.config.tar"
    $cloudInit  = Join-Path $RepoDir "cloud-init.yaml"
    $polis      = Join-Path $InstallDir "bin\polis.exe"

    foreach ($f in @($imagesTar, $configTar, $cloudInit)) {
        if (-not (Test-Path $f)) {
            Write-Err "Required file not found: $f"
            Write-Host "  Build first: cd $RepoDir; just build-windows"
            exit 1
        }
    }

    # ── Step 1: Create VM ─────────────────────────────────────────────────
    Write-Info "Creating VM with cloud-init..."
    & multipass launch 24.04 `
        --name polis `
        --cpus 2 `
        --memory 8G `
        --disk 40G `
        --cloud-init $cloudInit `
        --timeout 900
    if ($LASTEXITCODE -ne 0) { Write-Err "VM creation failed"; exit 1 }
    Write-Ok "VM created"

    Write-Info "Waiting for cloud-init..."
    & multipass exec polis -- cloud-init status --wait
    if ($LASTEXITCODE -ne 0) { Write-Err "cloud-init failed"; exit 1 }
    Write-Ok "cloud-init complete"

    # ── Step 2: Transfer config ───────────────────────────────────────────
    Write-Info "Transferring config tarball..."
    & multipass transfer $configTar polis:/tmp/polis-setup.config.tar
    if ($LASTEXITCODE -ne 0) { Write-Err "Failed to transfer config tarball"; exit 1 }

    & multipass exec polis -- tar xf /tmp/polis-setup.config.tar -C /opt/polis --no-same-owner
    if ($LASTEXITCODE -ne 0) { Write-Err "Failed to extract config tarball"; exit 1 }

    & multipass exec polis -- rm -f /tmp/polis-setup.config.tar

    # Write .env with version
    $cliVersion = (& $polis --version 2>&1) -replace '^polis\s+', ''
    $tag = "v$cliVersion"
    $envLines = @(
        "# Generated by install-dev.ps1",
        "POLIS_RESOLVER_VERSION=$tag",
        "POLIS_CERTGEN_VERSION=$tag",
        "POLIS_GATE_VERSION=$tag",
        "POLIS_SENTINEL_VERSION=$tag",
        "POLIS_SCANNER_VERSION=$tag",
        "POLIS_WORKSPACE_VERSION=$tag",
        "POLIS_HOST_INIT_VERSION=$tag",
        "POLIS_STATE_VERSION=$tag",
        "POLIS_TOOLBOX_VERSION=$tag"
    )
    $envContent = $envLines -join "`n"
    & multipass exec polis -- bash -c "printf '%s\n' '$envContent' > /opt/polis/.env"

    # Fix script permissions and strip Windows CRLF line endings
    & multipass exec polis -- find /opt/polis -name '*.sh' -exec chmod +x '{}' +
    & multipass exec polis -- find /opt/polis -name '*.sh' -exec sed -i 's/\r//' '{}' +
    Write-Ok "Config transferred"

    # ── Step 3: Load Docker images ────────────────────────────────────────
    Write-Info "Loading Docker images into VM..."
    & multipass transfer $imagesTar polis:/tmp/polis-images.tar.zst
    if ($LASTEXITCODE -ne 0) { Write-Err "Failed to transfer images tarball"; exit 1 }

    & multipass exec polis -- bash -c 'zstd -d /tmp/polis-images.tar.zst --stdout | docker load && rm -f /tmp/polis-images.tar.zst'
    if ($LASTEXITCODE -ne 0) { Write-Err "Failed to load Docker images"; exit 1 }
    Write-Ok "Docker images loaded"

    # Tag images with CLI version
    Write-Info "Tagging images as $tag..."
    $tagScript = 'docker images --format ''{{.Repository}}:{{.Tag}}'' | grep '':latest'' | while read -r img; do base=${img%%:*}; docker tag $img ${base}:' + $tag + '; done'
    & multipass exec polis -- bash -c $tagScript

    # Pull go-httpbin (small third-party test image)
    & multipass exec polis -- docker pull mccutchen/go-httpbin 2>$null

    # ── Step 4: Generate certs and secrets ────────────────────────────────
    Write-Info "Generating certificates and secrets..."
    & multipass exec polis -- sudo bash -c '/opt/polis/scripts/generate-ca.sh /opt/polis/certs/ca'
    & multipass exec polis -- sudo bash -c '/opt/polis/services/state/scripts/generate-certs.sh /opt/polis/certs/valkey'
    & multipass exec polis -- sudo bash -c '/opt/polis/services/state/scripts/generate-secrets.sh /opt/polis/secrets /opt/polis'
    & multipass exec polis -- sudo bash -c '/opt/polis/services/toolbox/scripts/generate-certs.sh /opt/polis/certs/toolbox /opt/polis/certs/ca'
    & multipass exec polis -- sudo bash -c '/opt/polis/scripts/fix-cert-ownership.sh /opt/polis'
    Write-Ok "Certificates and secrets ready"

    # ── Step 5: Start services ────────────────────────────────────────────
    Write-Info "Starting services..."
    & multipass exec polis -- bash -c 'cd /opt/polis && docker compose --env-file .env up -d --remove-orphans'
    if ($LASTEXITCODE -ne 0) { Write-Err "Failed to start services"; exit 1 }
    Write-Ok "Services started"

    # ── Step 6: Wait for workspace container to become healthy ────────────
    Write-Info "Waiting for workspace to become healthy (up to 120s)..."
    $maxAttempts = 60
    $healthy = $false
    for ($i = 1; $i -le $maxAttempts; $i++) {
        $json = & multipass exec polis -- docker compose -f /opt/polis/docker-compose.yml ps --format json workspace 2>$null
        if ($json) {
            $firstLine = ($json -split "`n")[0]
            try {
                $obj = $firstLine | ConvertFrom-Json -ErrorAction SilentlyContinue
                if ($obj.State -eq "running" -and $obj.Health -eq "healthy") {
                    $healthy = $true
                    break
                }
            } catch {}
        }
        Start-Sleep -Seconds 2
    }
    if ($healthy) {
        Write-Ok "Workspace is healthy"
    } else {
        Write-Warn "Workspace did not become healthy within 120s — check with: polis status"
    }
}

# ── Main ──────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "=== Polis Dev Installer ==="
Write-Host ""
Write-Info "Repo:        $RepoDir"
Write-Info "Install dir: $InstallDir"
Write-Host ""

Assert-Multipass
Install-Cli
Add-ToUserPath

# Remove existing VM for a clean reinstall
Write-Info "Checking for existing polis VM..."
$vmList = $null
$listJob = Start-Job { & multipass list --format csv 2>$null }
if (Wait-Job $listJob -Timeout 30) {
    $vmList = Receive-Job $listJob | Select-String -Pattern '^polis,'
} else {
    Stop-Job $listJob
    Write-Warn "multipass list timed out — assuming no existing VM"
}
Remove-Job $listJob -Force

if ($vmList) {
    Write-Info "Existing polis VM found — deleting for clean reinstall..."
    & multipass delete polis --purge 2>$null
    Write-Ok "VM deleted"
}
Remove-Item (Join-Path $InstallDir "state.json") -ErrorAction SilentlyContinue

Invoke-PolisInit

Write-Host ""
Write-Ok "Polis (dev build) installed successfully!"
Write-Host ""
