use anyhow::Result;

#[cfg(not(windows))]
use crate::infra::secure_fs::SecureFs;
#[cfg(not(windows))]
use anyhow::Context;

/// Abstracts creation of the SSH control-socket directory.
/// The production implementation ([`OsSocketsDir`]) creates the directory on
/// the filesystem.  In tests a `MockSocketsDir` (generated by `mockall`) can
/// be injected to verify call behaviour or simulate failures without touching
/// the real filesystem.
#[cfg_attr(test, mockall::automock)]
pub trait SocketsDir {
    /// Ensures the sockets directory exists with the correct permissions.
    /// # Errors
    /// Returns an error if the directory cannot be created or permissions set.
    fn ensure_exists(&self) -> Result<()>;
}

/// OS-backed implementation of [`SocketsDir`].
/// On Unix it creates `path` with permissions 700.  On Windows it is a no-op
/// because `ControlMaster` is not supported by Windows OpenSSH.
pub struct OsSocketsDir {
    #[cfg_attr(windows, allow(dead_code))]
    path: std::path::PathBuf,
}

impl OsSocketsDir {
    /// Creates an [`OsSocketsDir`] pointing at `path`.
    #[must_use]
    pub fn new(path: std::path::PathBuf) -> Self {
        Self { path }
    }
}

impl SocketsDir for OsSocketsDir {
    /// # Errors
    /// This function will return an error if the underlying operations fail.
    fn ensure_exists(&self) -> Result<()> {
        #[cfg(not(windows))]
        {
            std::fs::create_dir_all(&self.path)
                .with_context(|| format!("create dir {}", self.path.display()))?;
            SecureFs::set_permissions(&self.path, 0o700)?;
        }
        Ok(())
    }
}
