# Host init container — configures host iptables for TPROXY
FROM dhi.io/alpine-base:3.23-dev@sha256:2b318097756a2d92fb8fc059beaf512f8607224a17767d56e557618ca61296cb
RUN apk add --no-cache docker-cli iptables
